version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: cerulean
      POSTGRES_PASSWORD: cerulean
      POSTGRES_DB: cerulean
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cerulean
      SPRING_DATASOURCE_USERNAME: cerulean
      SPRING_DATASOURCE_PASSWORD: cerulean

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  db_data:
